version: "3"
services:
  database:
    image: postgres:9
    restart: always
    env_file:
      - .postgres.env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file: ./server/.env
    depends_on:
      - database
    networks:
      - default
    volumes:
      - avatar:/server/avatar
    ports:
      - "8080:8080"
volumes:
  data:
  avatar:
