ALTER TABLE "posts" DROP CONSTRAINT IF EXISTS fk0_author;
ALTER TABLE "comments" DROP CONSTRAINT IF EXISTS fk0_post;
ALTER TABLE "comments" DROP CONSTRAINT IF EXISTS fk1_author;
ALTER TABLE "upvotes" DROP CONSTRAINT IF EXISTS fk1_post;
ALTER TABLE "upvotes" DROP CONSTRAINT IF EXISTS fk2_author;
ALTER TABLE "downvotes" DROP CONSTRAINT IF EXISTS fk2_post;
ALTER TABLE "downvotes" DROP CONSTRAINT IF EXISTS fk3_author;

DROP TABLE IF EXISTS "users";
DROP TABLE IF EXISTS "posts";
DROP TABLE IF EXISTS "comments";
DROP TABLE IF EXISTS "upvotes";
DROP TABLE IF EXISTS "downvotes";